### ISSUE TITLE
convert_to = "ordinal_word"?

### ISSUE THREAD

**Issue by tiernanmartin** [CenterForAssessment/toOrdinal#30]
Great package!

Just wondering if you still plan to implement the "ordinal_word" option for the `convert_to` parameter.

Thanks!

**Comment by dbetebenner** [comment]
Thanks! Sorry for the slow reply. I've been wanting to do that but haven't found the time. This should give me the impetus. I'll shoot to have something in place by the end of the month.

**Comment by sspillane** [comment]
Hello. Really useful for me also this package. Thanks.
Have you had a chance to get the ordinal_word part complete? 
Thanks.

**Comment by ghost** [comment]
Hi all, check out the 'english' package if this is the only language you need. https://cran.r-project.org/web/packages/english/index.html
