### ISSUE TITLE
German does not have "0" support.

### ISSUE THREAD

**Issue by jefferickson** [CenterForAssessment/toOrdinal#8]
Now that `toOrdinal` accepts 0 as an input, the German implementation will break:

```
toOrdinal(0, language='German')
```

results in

```
Error in paste(cardinal_number, tmp.suffix, sep = "") : 
  object 'tmp.suffix' not found
```

**Comment by jefferickson** [comment]
I'm happy to fix it, but my German isn't good enough to know what the result should be.

**Comment by dbetebenner** [comment]
Thanks for the heads up on that bug. I know some German but what suffix one tacks on to zero for the ordinal abbreviation is beyond me.

I’ll poke around and see if I can come up with something.

Damian Betebenner
Center for Assessment
31 Mount Vernon Street
Dover, NH 03820

857-234-2474 (cell)
603-516-7900 (office)
603-516-7910 (fax)

dbetebenner@nciea.orgmailto:dbetebenner@nciea.org
@DBetebenner

On Mar 6, 2016, at 8:37 AM, Jeff Erickson <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm happy to fix it, but my German isn't good enough to know what the result should be.

**Comment by jefferickson** [comment]
I've e-mailed my Swiss friend to ask.

**Comment by dbetebenner** [comment]
Thanks!

**Comment by jefferickson** [comment]
My Swiss friend says that formally German only puts a full-stop after each cardinal to form the ordinal. For example, "1." "2." "3.", so the "0th" equivalent, in his mind would be "0.". He says that while the "-te" and "-ste" versions exist, they are informal. However, he did mention that the word for "zeroth" would be "nullte," which to me would imply that we go with "-te" instead of "-ste" if you choose to keep that version. 

Interesting side note, Swedish used to use the full-stop version, but no longer does.

**Comment by dbetebenner** [comment]
Very interesting. I have to remember that: nullte. Thanks!
